# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Pome.ro'
tagline:          'Tom Pomeroy'
description:      'A blog about Tech, Code, Games, and whatever else is in my head.'
url:              http://pome.ro
baseurl:          http://pome.ro/

author:
  name:           'Tom Pomeroy'
  url:            https://github.com/AmazingWizard

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AmazingWizard
